# This is an example of a graderutils configuration file that you use to control test execution and result parsing
# This file is very verbose on purpose.
# The only required key in a test config yaml is the list of Python module names that should be executed as tests, everything else is optional

# List of test modules which should be executed.
# At least one must be specified.
# Modules are executed in the same order as they have been specified in this list.
test_modules:
    # The module key should contain the name of an importable Python module which contains at least one unittest.TestCase class.
  - module: local_tests
    description: Local tests
    # You can use several modules to group tests of different types
  - module: grader_tests
    description: Grader tests

# (Optional)
# Paths to custom Jinja2 HTML templates to be used instead of the default ones found in graderutils/static.
error_template: ./my_error_template.html
feedback_template: ./my_feedback_template.html

# Optional file validation
# All errors from failed validation are passed to the error template.
# If there are no errors, i.e. all validations pass, nothing is done.

validation:
  # Try importing my_solution as a Python module, catch all exceptions and pass them to the error template.
  - type: python_import
    file: my_solution.py
  # Set restricted syntax which should not be found in file.
  # If such syntax is found, pass data of found matches to the error template.
  - type: python_blacklist
    file: my_solution.py
    # By default, if a validation task fails, validation is stopped and feedback is shown for the failed task.
    # break_on_fail allows showing several failed validation tasks after validation is complete.
    break_on_fail: False
    message: "In this exercise, some builtin syntax related to lists is not allowed, since you should make you own list implementation."
    # Names of abstract syntax tree nodes and custom messages which are shown if nodes are found in the submitted file.
    # A comprehensive list of AST nodes can be found here: https://greentreesnakes.readthedocs.io/en/latest/nodes.html
    node_names:
      ListComp: List comprehensions
      For: For loops
    # Optionally, define exact strings returned by ast.dump, which are not allowed.
    # The graderutils.validation module contains a simple ast_dump function for dumping all ast nodes of a given source string.
    node_dumps:
      "Name(id='list', ctx=Load())": Loading the list builtin
    # If a full ast.dump string match is too specific, it can be 'softened' using regexp.
    # You have to do escaping by yourself, though.
    node_dump_regexp:
      "^Attribute.*attr\\=\\'sort\\'\\,\\ ctx\\=Load\\(\\)": Loading the sort method
  # Simple regexp-based substring blacklisting.
  - type: plain_text_blacklist
    file: my_solution.sql
    # If ignorecase is True, all keys in strings dict must be in lowercase
    ignorecase: True
    strings:
      drop: Dropping tables
      delete: Deleting entries

  # More validation options

  # Whitelists are inverted blacklists, where all node names and node dumps are restricted, unless specified in the whitelist.
  # There are no exceptions, if the node is not in included in the whitelist and it is in the submitted module, it will not be accepted.
  # The messages in node_names and node_dumps are ignored, but you can provide a message in 'message'.
  - type: python_whitelist
    file: my_solution.py
    message: "You should only submit closed form equations, other kind of syntax is not allowed in this exercise."
    node_names:
      # Node messages are ignored for whitelists and the name of the missed node will be used instead.
      Module: Module
      Assign: Assigning values to names
      # Storing and loading names/variables
      Name: Using names
      Load: Loading a name
      Store: Storing a name
      # Bitwise operations and matrix multiplication are not included
      BinOp: Binary operations
      Add: Addition
      Sub: Subtraction
      Mult: Multiplication
      Div: Division
      FloorDiv: Floor division
      Mod: Modulo
      Pow: Power

# Optional traceback hiding
# If an exception from the class_names list of exception classes is raised, its traceback is removed from the output and leave only the exception line.
#
# e.g. with AssertionError:
#
# Traceback (most recent call last):
#   File "local_tests.py", line 33, in test_is_prime_with_no_primes
#    "{:d} is not a prime number, but your function says it is".format(value)
# AssertionError: True is not false : -1 is not a prime number, but your function says it is
#
# only the following will be displayed:
#
# AssertionError: True is not false : -1 is not a prime number, but your function says it is
#
# If remove_more_sentinel is given, then everything starting from the exception line ending at the sentinel, will also be removed.
#
# e.g. with AssertionError and remove_more_sentinel [remove-stop]:
#
# Traceback (most recent call last):
#   File "local_tests.py", line 33, in test_is_prime_with_no_primes
#    "{:d} is not a prime number, but your function says it is".format(value)
# AssertionError: True is not false : [remove-stop]-1 is not a prime number, but your function says it is
#
# turns into just:
#
# -1 is not a prime number, but your function says it is
#
traceback_to_hide:
    # Specify names of exception classes that should have their traceback hidden
    class_names:
        - AssertionError
        - mymodule.ClassifiedException
    # (Optional) If given and of non-zero length, strip beginning of each exception line up until and including this string.
    # See example above
    remove_more_sentinel: "[remove-stop]"
    # (Optional) If given and True, exception tracebacks in the full console output string will not be hidden, only in feedback for individual test cases
    keep_tracebacks_in_full_output: True
    # (Optional) If given and of non-zero length, hidden tracebacks will be replaced with this string.
    # Does not insert a newline, append '\n' if e.g. AssertionError should be on its one line.
    replacement_string: "## Traceback removed ##"
